### ISSUE TITLE
initiate trendecon keywords for DE

### ISSUE THREAD

**Issue by christophsax** [trendecon/trendecon#32]
keywords <- c("Wirtschaftskrise", "Kurzarbeit", "arbeitslos", "Insolvenz")

See [second vignette](https://trendecon.github.io/trendecon/articles/daily-series.html) for how to.

And push results to:

https://github.com/trendecon/data

**Comment by christophsax** [comment]
@vzei @angelicambg @ronaldindergand @izmartinez @ninamuehlebach 

The setup for different countries is ready.

We have now some documentation and everyone should be able to contribute.

If unclear, please help improving the documentation in https://github.com/trendecon/trendecon/blob/master/vignettes/daily-series.Rmd and send a pull request.

@uwethuemmel has written the documentation and knows how these things work.

**Comment by vzei** [comment]
Some feedback on the "Introduction to trendecon" vignette:
-  "The popularity of a search term can be analysed over time, across regions and relative to other search terms." -> I would write "relative popularity" because many people don't know that there are no absolute search numbers. You might even add a sentence spelling this out.
- It would be nice to get an argument for the procedure and some intuition for the following sentence: "It wraps around the package gtrendsR but modifies the function [gtrendsR::gtrends()] by a) vectorizing it, b) converting the result to a tsboxable tibble and c) retrying if no result is returned."
- "The frequency of the data depends on the entered time span.": Do I understand it correctly that you cannot choose your own time-span? Why do we not allow for it? 
- It would be nice to show a figure and the code to combine the lines for the last two figures. 

Thanks for all the work!

**Comment by christophsax** [comment]
Thanks Vera. Could you do a suggestion an PR? :-)

**Comment by vzei** [comment]
@christophsax I don't understand - a suggestion for which element? These are all suggestions: nothing urgent but things I noted when I looked at it. And one of the comments was not useful at all I realized.
Regarding the first point, we could write:
"The relative popularity of a search term can be compared over time, across regions, and to other search terms. Google does not provide information about the absolute number of Google searches for any given search term."

**Comment by christophsax** [comment]
You could edit the `.Rmd` file with your suggested changes:

https://github.com/trendecon/trendecon/blob/master/vignettes/intro.Rmd

Perhaps easier to do this in the browser:

<img width="463" alt="image" src="https://user-images.githubusercontent.com/1390827/84895703-03e94b00-b0a3-11ea-80fd-0b3e49b132d8.png">

and do a pull request on a separate branch:

<img width="936" alt="image" src="https://user-images.githubusercontent.com/1390827/84895562-ca184480-b0a2-11ea-8b13-c25b4d58ab5a.png">

So, we (@ninamuehlebach, @uwethuemmel, @angelicambg or I) can review and accept or not.

As a first-time reader, you are the perfect co-author for this vignettes. It would be nice if we could make this more interactive.

**Comment by vzei** [comment]
I suggested some changes and made some comments in the text with suggestions/questions

**Comment by uwethuemmel** [comment]
@vzei I commented directly in https://github.com/trendecon/trendecon/commit/d1765a3b162d998f3920b35644ef10cba51fe73a

**Comment by KKPMW** [comment]
@christophsax this is done now. The processed and raw data is in trendecon/data repo.
