### ISSUE TITLE
Bug with proc_index & ts_gtrends_mwd

### ISSUE THREAD

**Issue by johannes97s** [trendecon/trendecon#67]
Hello, 
thank you for providing the R Code for your Index. We tried to get daily data but there occured two bugs.
At first we called
proc_keyword_init("arbeitslos", "DE")
proc_index("arbeitslos", "DE", "arbeitslos_ind").
The first worked well, but after calling the second we get an Error

Fehler: Cannot open file for writing:                                                                                    
'C:\Users\S********\Documents\ifwtrends\raw\de\arbeitslos_d.csv' 

but the file ist definitely there. 

And we also tried 
ts_gtrends_mwd("amazon", "DE"), but there occured

Fehler in tempdisagg::td(ww ~ dd, method = "fast", conversion = "mean") : 
  right hand side contains NAs

Could you pls give as a hint what we are doing wrong. 

Working with R 4.0.3. (Also tried with 4.1.0)
Importing
library(tidyverse)
library(gtrendsR)
library(trendecon)
library(tsbox)
library(openxlsx)
library(corrr)
library(lubridate)

**Comment by karoliskoncevicius** [comment]
Seems like this is the same issue as #62

**Comment by karoliskoncevicius** [comment]
@johannes97s thank you for reporting the issue. The first issue you reported (about the not-available file name) cannot be reproduced on my end. Can you double check if there are no restricted permissions in the folder you were trying to use?

Regarding the second issue - it is now fixed as a side effect of fixing #62 and you can read more about it there. One note - even thou `proc_keyword_init` worked, and it was `proc_keyword` that gave you the error - the real issue was with `proc_keywrod_init`, as it produced data with missing days. So if you have errors make sure to rerun `proc_keyword_init`.
