### ISSUE TITLE
Interpreting the results from the trendecon package

### ISSUE THREAD

**Issue by Je-gh** [trendecon/trendecon#74]
Dear trendecon developers,

Thank you so much or creating this easy to use R package and for writing a very interesting paper around it!  

IF you do not mind, I have some questions about interpreting the output results/graph that the package returns after a google search query. Namely, I am struggling to understand what it means when an observation for the daily data goes below zero or goes above 100, as the Google Trends data is capped between 0 and 100. I understand that the Chow and Lin method requires that the mean of the high frequency data must be consistent with the low frequency one (as explained in your scientific paper), but I still do not grasp what for example a value of -40 on 13 June 2017 or +150 on 17 Septemebr 2016 for "shoes" means (sorry for the silly example). Does it mean that compared to the average, the search of "shoes" is much lower/higher than normal on these dates? If yes, where is this average coming from (or more simply put, what do the y-axis on the trendecon website represent)? In addition, for example, if we have a regression of BuyingShoes = b0 + b1*TrendEcon + e (where BuyingShoes is how many shoes were bought for a certain period in Switzerland and TrendEcon is the search term for "shoes" in Switzerland) would the interpretation for a positive/negative b1 coefficient be straightforward?

Thank you in advance!

**Comment by christophsax** [comment]
@karoliskoncevicius, could you have a look at these questions? Thanks a lot!

**Comment by karoliskoncevicius** [comment]
Hello @Je-gh and thank you for reaching out,

I will try to answer the questions below:

> I am struggling to understand what it means when an observation for the daily data goes below zero or goes above 100, as the Google Trends data is capped between 0 and 100.

You are correct here, google data is relative and it returns values between 0 and 100. This makes it so that the values are relative within the investigated time frame. From example, if the google query was for the time window 2006-2022 - one date might get a value of 100, however if we changed to time frame to, say, 2020-2022, another day (highest within this narrower time frame) would be assigned a value of 100. Same for the value of 0. Bottom line - values returned by google are only relative.

> but I still do not grasp what for example a value of -40 on 13 June 2017 or +150 on 17 Septemebr 2016 for "shoes" means (sorry for the silly example).

This is caused by the step which combines multiple keywords into a single "category". For shoes - you can inspect the "info" tab for that graph on our website, and it will list the keywords that comprise the "shoe" category. So note that for single keyword (like the "cinema" example of trendecon REDME page) the returned values do range from 0 to 100.

For multiple keywords there is additional combining step that needs to be taken. It is currently implemented via the use of the first principal component, as described [HERE](https://trendecon.github.io/trendecon/articles/daily-series.html#step-4-combining) with the idea that the first principal component will extract the most variable (read informative) common trend present in all the combined keywords. First step of princical component procedure is centering the data (subtracting the series-specific mean from each date in that series). This causes, roughly, half the days have values above 0 and half the days below 0. And that's why the values can get both positive and negative scores.

> Does it mean that compared to the average, the search of "shoes" is much lower/higher than normal on these dates?

The interpretation stays the same as with original google data, except now, instead of having values ranging from 0 to 100, we have values ranging from some negative number to some positive number. There is no additional interpretation needed. So for example, a value pair of -1 and 2 would be close together than, say, 7 and 30. The signs themselves carry no additional information, when comparing only compare the values and how close or far away they are.

> If yes, where is this average coming from (or more simply put, what do the y-axis on the trendecon website represent)?

Just with original google data, the represented values are relative and should be compared between dates. The only difference is the range change, not from 0 to 100, but from, say, -50 to 50.

In addition, for example, if we have a regression of BuyingShoes = b0 + b1*TrendEcon + e (where BuyingShoes is how many shoes were bought for a certain period in Switzerland and TrendEcon is the search term for "shoes" in Switzerland) would the interpretation for a positive/negative b1 coefficient be straightforward?

The interpretation of the sign of b1 stays the same, because the direction is not changed. The days that had highest values on the scale 0-100 will still have highest values, just on a different scale. So a positive b1 coefficient would mean that higher search terms for "shoes" increased the number of shoes bought, while a negative coefficient would say the opposite - higher search terms decreased the number of shoes bought. The magnitude of the coefficient itself is hard to interpret, because we cannot express it in terms of number of actual keyword searches, but that stays the same regardless of the scale: 0:100, or -50:50, or -20:120, etc.

Additionally, if you want to go back to 0:100 range, you can so so with a simple transformation, that turns the lowest value to be 0, highest value to be 100, and all the rest in between, i.e. as described [HERE](https://stats.stackexchange.com/a/351703/18417)

Finally, in case you are performing regression on standardised variables (z-scores after subtracting the mean and dividing by standard deviation), there should be no difference between the ranges used to represent the values.

Let me know if this adequately addresses your question, or if you would like to hear further details.

**Comment by Je-gh** [comment]
@karoliskoncevicius Thank you a ton for your extensive and thorough answers, I really appreciate the time you've spent on all of my questions!!! It all makes sense to me now and I do not have any follow-up questions. Thank you for developing the R package and the paper with your team and I wish you all the best with future endeavors!
