### ISSUE TITLE
too many requests

### ISSUE THREAD

**Issue by RogerRendon** [trendecon/trendecon#89]
Hi, só I started to use trendecon yesterday, made 3 full requests at most. And today made one more. After that I started receiving **Server is not accepting requests**, the lib makes its 10 trials with no success, I already tried to wait 1 and 2 hours. but still no success. Anyone else passed through this? How can I solve it?  I'm already using a VPN and a dynamic IP Address. 

Thanks in advance to anyone, that takes time to help me solve this prob.

**Comment by karoliskoncevicius** [comment]
Hello @RogerRendon,

This is a valid question, however, the issue here is not with `trendecon`. The package is merely asking for data from the server, and when the server doesn't return for whatever reason all we can do is spell out that reason (i.e. "server is not accepting requests") and try again. If after waiting pauses and 10 additional trials the issue persists this means the download will probably not succeed again fro some time.

In my experience it takes around a day (so 24 hours, not 1 or 2 hours) for the downloading to resume again for the same computer + ip address. With one machine you said you made 3 full downloads. I usually am able to go through 5 complete downloads before the server ignores me. I use 3 different machines for downloading so this equals to 15 full downloads.

You can increase this number if you don't really need the data for the full period. In that case you can set the date (`from=` and `to=`) of interest and one full download will consist of fewer requests, hence you will be able to complete more of them.

Also please note that this issue is present when you are downloading a lot of new data. If you already have the data and want to update it - it takes a lot fewer requests and you would be able to update hundreds of downloaded datasets without issue (see our vignette here: https://github.com/trendecon/trendecon/blob/master/vignettes/daily-series.Rmd)

Hope this helps.

**Comment by RogerRendon** [comment]
Hi, @karoliskoncevicius. Indeed, tried again this morning and I succeeded the download. Thank you for the quick response! BTW this is a great lib!
