### ISSUE TITLE
Time function not working

### ISSUE THREAD

**Issue by NathanDB99** [trendecon/trendecon#90]
Hello, first of all thanks for creating this package, it was brought to my attention by Eichenauer et al. (2021) and seems very promising. 

When running the following code (with any time value chosen):

x3 <- trendecon::ts_gtrends_mwd(keyword = "cinema", 
              geo = "CH", 
              time = "today 12-m"
              )

I will get the error:

Error in trendecon::ts_gtrends_mwd(keyword = "cinema", geo = "CH", time = "today 12-m") : 
  unused argument (time = "today 12-m")

**Comment by karoliskoncevicius** [comment]
Hello,

This is because the function you are calling - `ts_gtrends_mwd()` doesn't have an argument "time".
Please see `args(ts_gtrends_mwd)` and `help(ts_gtrends_mwd)`.

The `time` argument is an argument in the original package `gtrends`. `trendecon` downloads the data repeatedly over a long period and you have to specify the starting date, and the end date, for the period of interest. For example, if you want to download all the data from your selected date up to today, you can call the function like so:

    trendecon::ts_gtrends_mwd("cinema", geo = "CH", from = "2022-01-01")

If you also want to download the data only for half a year (as an example) of 2022, then you would do:

    trendecon::ts_gtrends_mwd("cinema", geo = "CH", from = "2022-01-01", to = "2022-06-01")

Hope this helps!
