### ISSUE TITLE
Error ts_gtrends_mwd  "widget$status_code == 200 is not TRUE"

### ISSUE THREAD

**Issue by 5000cb** [trendecon/trendecon#91]
Hi, 

When I run 

`X<-ts_gtrends_mwd("X", geo="US", from="2013-01-01", to="2022-12-31")`

I get the following error message 

Error in `mutate()`:
! Problem while computing `trend_data = list(...)`.
ℹ The error occurred in row 92.
Caused by error in `get_widget()`:
! widget$status_code == 200 is not TRUE

Any idea how to solve it? 

Thanks, 

C.

**Comment by karoliskoncevicius** [comment]
Hello @5000cb - can you post more details (full code which led to the error you are seeing)? Now, for example, your code line is not valid - there is no such function `ts_gtrends_wd()` in trendecon.

And when I use `ts_gtrends_mwd` I cannot reproduce this error - everything works as expected.

Interestingly the error you are showing (the one about get_widget) is coming from gtrends package, and not trendecon.

Currently I am trying to update all the packages to the newest versions and try again, see if the changes in gtrends or someplace else could have caused something to break. More information soon.

**Comment by karoliskoncevicius** [comment]
Updated the packages and it still works without errors. R version 4.2.2.

If you see this error persistently, please first try to update R to the newest version and then update all of the installed packages with, for example, `update.packages(ask=FALSE)` and after that try again.

For now I will mark this issue as non-reproducible, but will leave it open.

**Comment by 5000cb** [comment]
Hello @karoliskoncevicius

Thanks for you quick reply. Indeed, there was a missing "m" in the code I copied in my first post. I tried to update everything (R and all installed packages), and it works now! 

I have two more questions regarding the`ts_gtrends_mwd` function:
- Could you confirm that specifying `geo=""` is the same than selecting "worldwide" on the Google Trends web interface? 
- In the Google Trends web interface, it is possible to search for "X" either as a "search term" or as a "topic", is it possible to search for "topic" with the function? 

Thanks in advance.

Best, 

C.

**Comment by karoliskoncevicius** [comment]
Hello, glad it is working now.

Just a note - separate questions are better addressed as separate issues, that way it is easier to keep everything organised.

RE the selection of "worldwide" - `trendecon` passes the `geo=z` argument upstream to the `gtrendsR` package. According to the documentation I've seen from them you have to specify `geo=""`. So your function call should be `ts_gtrends_mwd(keyword, geo="")`. Note - do not leave the `geo=` argument missing, because in that case it will default to `CH` (that is the difference between `trendecon` and `gtrendsR`. I double checked the wordl-wide results some time ago and they seemed to be correct, so I have to assume this is working. But if it stops working for some reason or returns the wrong values it will likely be because of something `gtrendsR` packages does, not us. Again - we for obtaining the actual results in the end we are depending on `gtrendsR`. Related issue here: https://github.com/trendecon/trendecon/issues/80

**Comment by karoliskoncevicius** [comment]
RE topic search - we have searches for keywords and categories, but not for topics. It would be quite hard to implement too. However, having said that, seems like there is a work-around. According to this discussion on `gtrendsR` GitHub page: https://github.com/PMassicotte/gtrendsR/issues/92 you can decode the topic search into a keyword and then pass that keyword to the function. The keyword will look something like this: `"/m/058s44"`. 

Also please take a look at this additional package - https://github.com/mamut86/GTT - which was introduced at the end of the discussion about topic searches. Seems like it can convert topics of interest into search strings. If that is the case, then you should just pass the generated topic string to the `trendecon` functions as a keywords and get the results for the topic.

I would double-check at least once if this works, just to be sure, maybe with the example given in the `gtrendsR` discussion.
Just do a search for a topic and see if it trend matches the one returned by google. Can be for a narrow time periods, like one year, to not waste your bandwidth and google download limits.

Hope this helps. If you have further unrelated questions, please open a separate issue, as then it is easier for other people with the same questions to find the answers.
