### ISSUE TITLE
Error in  ts_gtrends_mwd

### ISSUE THREAD

**Issue by FelipeMT5** [trendecon/trendecon#93]
Hello everyone!
I'm trying to use the daily data using the following TrendEcon code:
```
indice_gt_diario <- ts_gtrends_mwd("ibovespa",
                                    to = Sys.Date(),
                                    geo = "BR")
```

But I'm getting this error:

```
Error in `mutate_cols()`:
! Problem with `mutate()` column `trend_data`.
i `trend_data = list(...)`.
x Retries exhausted!
i The error occurred in row 182.
Caused by error in `gtrends_with_backoff()`:
! Retries exhausted!
Run `rlang::last_error()` to see where the error occurred.
```

Could someone help me?
Thanks in advance for the help.

**Comment by karoliskoncevicius** [comment]
Hello @FelipeMT5 

This error tells you that the Google server does not allow you to download any more data today. They think you already downloaded a lot and they added temporary restrictions on your IP address. See these related issues: https://github.com/trendecon/trendecon/issues/79 https://github.com/trendecon/trendecon/issues/89

Note that this is not a problem with `trendecon`, as there is nothing we can do to change Google's download policies. What you can do is 1) try downloading from a different computer using a different IP address, 2) wait one day and then try again.

I assume if you will run the same function again, today, everything will work without problems. But, since I see you are downloading data for a full period - and this is many requests - Google will soon restrict your IP again. So what I would recommend, in case you are interested only in a certain period, is to set the `from=` and `to=` arguments. For example, if you only need data for the last 2 years you can call this function like so:

    indice_gt_diario <- ts_gtrends_mwd("ibovespa", from="2021-01-01", geo="BR")
    
This way you will be able to download more keywords, until exhausting the daily limit and reaching Google restriction.
